## Необходимые импорты

In [ ]:
!pip install catboost -q
!pip install ipywidgets -q
!pip install notebook

In [1]:
import ipywidgets as widgets
widgets.IntSlider()

IntSlider(value=0)

In [2]:
from catboost.datasets import titanic

import numpy as np

from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier, Pool, metrics, cv
from sklearn.metrics import accuracy_score

In [24]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\e.karandashova.INSIDE\AppData\Local\anaconda3\envs\py11\Lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\e.karandashova.INSIDE\AppData\Local\anaconda3\envs\py11\Lib\site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.0/8.1 MB 1.5 MB/s eta 0:00:05
   ------ --------------------------------- 1.3/8.1 MB 1.5 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.1 MB 1.5 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.1 MB 1.5 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.1 MB 1.5 MB/s eta 0:00:04
   ------------ --------------------------- 2.6/8.1 MB 1.4 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.1 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 3.9/8.1 MB 1.5 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.1 MB 1.5 MB/s eta 0:00:03
   ---------------------- ----------------- 4.5/8.1 MB 1.5 MB/s eta 0:00:03
   ----------------------- ---------------- 4.7/8.1 MB 1.4 MB/s eta 0:00:03
   ------------------------- -------------- 5.2/8.1 MB 1.5 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 1.5 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.1 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.1 MB 1.6 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 1.6 MB/s  0:00:05
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 threadpoolctl-3.6.0

## Загрузка данных

In [3]:
train_df, test_df = titanic()

train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Обработка данных

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [5]:
num_value_stats = train_df.isnull().sum(axis = 0)
num_value_stats[num_value_stats != 0]

Age         177
Cabin       687
Embarked      2
dtype: int64

In [6]:
num_value_stats = test_df.isnull().sum(axis = 0)
num_value_stats[num_value_stats != 0]

Age       86
Fare       1
Cabin    327
dtype: int64

### Заполним пропуски значением -999

In [7]:
# Выбираем только те колонки, у которых тип 'string'
string_cols = train_df.select_dtypes(include='string').columns

# Применяем преобразование
train_df[string_cols] = train_df[string_cols].astype(object)
test_df[string_cols] = test_df[string_cols].astype(object)

In [8]:
train_df.fillna(-999, inplace = True)
test_df.fillna(-999, inplace = True)

### Разобьем данные на матрицы X и y

In [9]:
X = train_df.drop('Survived', axis = 1)
y = train_df.Survived

In [10]:
X.dtypes

categorical_features_indices = np.where(X.dtypes != float)[0]

In [11]:
categorical_features_indices

array([ 0,  1,  2,  3,  5,  6,  7,  9, 10])

In [12]:
X

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,-999,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,-999,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,-999,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,-999,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,-999.0,1,2,W./C. 6607,23.4500,-999,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,-999,Q

### Разобьем данные на трейн и валидацию

In [13]:
Xtrain, Xval, ytrain, yval = train_test_split(X, y, train_size=0.75, random_state=42)

Xtest = test_df

In [14]:
model = CatBoostClassifier(
    custom_loss=[metrics.Accuracy()],
    random_seed=42
)

In [15]:
model.fit(
    Xtrain, ytrain,
    cat_features=categorical_features_indices,
    eval_set=(Xval, yval),
    logging_level='Silent', # хотим ли мы видеть метрики на каждой итерации
    plot = True
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

CatBoostClassifier(custom_loss=['Accuracy'], random_seed=42)

### Оценим качество по кросс-валидации

In [39]:
cv_params = model.get_params()
cv_params.update({
    'loss_function': metrics.Logloss()
})
cv_data = cv(
    Pool(X, y, cat_features=categorical_features_indices),
    cv_params,
    logging_level='Silent',
    plot=True
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [40]:
print('Best validation accuracy score: {:.2f}±{:.2f} on step {}'.format(
    np.max(cv_data['test-Accuracy-mean']),
    cv_data['test-Accuracy-std'][np.argmax(cv_data['test-Accuracy-mean'])],
    np.argmax(cv_data['test-Accuracy-mean'])
))

Best validation accuracy score: 0.83±0.02 on step 355

### Применяем обученную модель

In [42]:
pred = model.predict(Xtest)
pred_prob = model.predict_proba(Xtest)
print(pred[:10])
print(pred_prob[:10])

[0 0 0 0 1 0 1 0 1 0]
[[0.85473931 0.14526069]
 [0.76313031 0.23686969]
 [0.88972889 0.11027111]
 [0.87876173 0.12123827]
 [0.3611047  0.6388953 ]
 [0.90513381 0.09486619]
 [0.33434185 0.66565815]
 [0.78468564 0.21531436]
 [0.39429048 0.60570952]
 [0.94047549 0.05952451]]

### Улучшение предсказаний и др. возможности CatBoost

#### Early Stopping

In [46]:
model.fit(
    Xtrain, ytrain,
    cat_features=categorical_features_indices,
    eval_set=(Xval, yval),
    early_stopping_rounds=30, # если начало ухудшаться кач-во, модель обучается еще 30 деревьев. По умолчанию 1000
    logging_level='Verbose', # если хотим видеть метрики на каждой итерации
    plot = True
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.028683
0:	learn: 0.6739988	test: 0.6742630	best: 0.6742630 (0)	total: 25.3ms	remaining: 25.3s
1:	learn: 0.6589013	test: 0.6592240	best: 0.6592240 (1)	total: 39.3ms	remaining: 19.6s
2:	learn: 0.6421502	test: 0.6426778	best: 0.6426778 (2)	total: 63.3ms	remaining: 21s
3:	learn: 0.6297276	test: 0.6302310	best: 0.6302310 (3)	total: 83.7ms	remaining: 20.8s
4:	learn: 0.6147184	test: 0.6198228	best: 0.6198228 (4)	total: 110ms	remaining: 21.9s
5:	learn: 0.6017730	test: 0.6073627	best: 0.6073627 (5)	total: 133ms	remaining: 22s
6:	learn: 0.5885309	test: 0.5956000	best: 0.5956000 (6)	total: 154ms	remaining: 21.9s
7:	learn: 0.5783200	test: 0.5858523	best: 0.5858523 (7)	total: 178ms	remaining: 22s
8:	learn: 0.5665895	test: 0.5743842	best: 0.5743842 (8)	total: 203ms	remaining: 22.4s
9:	learn: 0.5575381	test: 0.5662283	best: 0.5662283 (9)	total: 227ms	remaining: 22.5s
10:	learn: 0.5491045	test: 0.5575176	best: 0.5575176 (10)	total: 249ms	remaining: 22.4s
11:	learn: 0.5423887	test: 0.5505905	best: 0.5505905 (11)	total: 265ms	remaining: 21.8s
12:	learn: 0.5354629	test: 0.5428797	best: 0.5428797 (12)	total: 283ms	remaining: 21.5s
13:	learn: 0.5283279	test: 0.5360937	best: 0.5360937 (13)	total: 300ms	remaining: 21.1s
14:	learn: 0.5217501	test: 0.5293872	best: 0.5293872 (14)	total: 320ms	remaining: 21s
15:	learn: 0.5157272	test: 0.5239492	best: 0.5239492 (15)	total: 340ms	remaining: 20.9s
16:	learn: 0.5089750	test: 0.5185852	best: 0.5185852 (16)	total: 362ms	remaining: 20.9s
17:	learn: 0.5032451	test: 0.5128041	best: 0.5128041 (17)	total: 387ms	remaining: 21.1s
18:	learn: 0.4970473	test: 0.5071751	best: 0.5071751 (18)	total: 409ms	remaining: 21.1s
19:	learn: 0.4921670	test: 0.5028565	best: 0.5028565 (19)	total: 423ms	remaining: 20.7s
20:	learn: 0.4874681	test: 0.4980757	best: 0.4980757 (20)	total: 446ms	remaining: 20.8s
21:	learn: 0.4846683	test: 0.4955481	best: 0.4955481 (21)	total: 469ms	remaining: 20.8s
22:	learn: 0.4800381	test: 0.4916634	best: 0.4916634 (22)	total: 494ms	remaining: 21s
23:	learn: 0.4752794	test: 0.4882002	best: 0.4882002 (23)	total: 518ms	remaining: 21.1s
24:	learn: 0.4716137	test: 0.4852624	best: 0.4852624 (24)	total: 533ms	remaining: 20.8s
25:	learn: 0.4688795	test: 0.4824286	best: 0.4824286 (25)	total: 540ms	remaining: 20.2s
26:	learn: 0.4646352	test: 0.4794211	best: 0.4794211 (26)	total: 554ms	remaining: 20s
27:	learn: 0.4622311	test: 0.4769201	best: 0.4769201 (27)	total: 560ms	remaining: 19.4s
28:	learn: 0.4584013	test: 0.4743519	best: 0.4743519 (28)	total: 572ms	remaining: 19.2s
29:	learn: 0.4535304	test: 0.4717948	best: 0.4717948 (29)	total: 586ms	remaining: 18.9s
30:	learn: 0.4507849	test: 0.4696368	best: 0.4696368 (30)	total: 599ms	remaining: 18.7s
31:	learn: 0.4497374	test: 0.4685335	best: 0.4685335 (31)	total: 607ms	remaining: 18.4s
32:	learn: 0.4480931	test: 0.4673465	best: 0.4673465 (32)	total: 621ms	remaining: 18.2s
33:	learn: 0.4446326	test: 0.4648279	best: 0.4648279 (33)	total: 635ms	remaining: 18s
34:	learn: 0.4425685	test: 0.4629505	best: 0.4629505 (34)	total: 648ms	remaining: 17.9s
35:	learn: 0.4410080	test: 0.4615814	best: 0.4615814 (35)	total: 659ms	remaining: 17.6s
36:	learn: 0.4385623	test: 0.4598132	best: 0.4598132 (36)	total: 672ms	remaining: 17.5s
37:	learn: 0.4363624	test: 0.4580388	best: 0.4580388 (37)	total: 686ms	remaining: 17.4s
38:	learn: 0.4346195	test: 0.4568825	best: 0.4568825 (38)	total: 694ms	remaining: 17.1s
39:	learn: 0.4331800	test: 0.4556787	best: 0.4556787 (39)	total: 706ms	remaining: 17s
40:	learn: 0.4304897	test: 0.4540201	best: 0.4540201 (40)	total: 719ms	remaining: 16.8s
41:	learn: 0.4283415	test: 0.4528728	best: 0.4528728 (41)	total: 732ms	remaining: 16.7s
42:	learn: 0.4265080	test: 0.4517417	best: 0.4517417 (42)	total: 744ms	remaining: 16.6s
43:	learn: 0.4255831	test: 0.4522028	best: 0.4517417 (42)	total: 756ms	remaining: 16.4s
44:	learn: 0.4252895	test: 0.4518594	best: 0.4517417 (42)	total: 761ms	remaining: 16.2s
45:	learn: 0.4232907	test: 0.4509524	best: 0.4509524 (45)	total: 772ms	remaining: 16s
46:	learn: 0.4219785	test: 0.4502040	best: 0.4502040 (46)	total: 784ms	remaining: 15.9s
47:	learn: 0.4203940	test: 0.4490914	best: 0.4490914 (47)	total: 797ms	remaining: 15.8s
48:	learn: 0.4194225	test: 0.4479678	best: 0.4479678 (48)	total: 808ms	remaining: 15.7s
49:	learn: 0.4179930	test: 0.4468923	best: 0.4468923 (49)	total: 820ms	remaining: 15.6s
50:	learn: 0.4167287	test: 0.4462036	best: 0.4462036 (50)	total: 833ms	remaining: 15.5s
51:	learn: 0.4155112	test: 0.4452557	best: 0.4452557 (51)	total: 845ms	remaining: 15.4s
52:	learn: 0.4145264	test: 0.4441310	best: 0.4441310 (52)	total: 858ms	remaining: 15.3s
53:	learn: 0.4129348	test: 0.4433545	best: 0.4433545 (53)	total: 870ms	remaining: 15.2s
54:	learn: 0.4113962	test: 0.4420501	best: 0.4420501 (54)	total: 883ms	remaining: 15.2s
55:	learn: 0.4097377	test: 0.4401631	best: 0.4401631 (55)	total: 896ms	remaining: 15.1s
56:	learn: 0.4088380	test: 0.4395241	best: 0.4395241 (56)	total: 908ms	remaining: 15s
57:	learn: 0.4069748	test: 0.4379574	best: 0.4379574 (57)	total: 920ms	remaining: 14.9s
58:	learn: 0.4051131	test: 0.4357254	best: 0.4357254 (58)	total: 934ms	remaining: 14.9s
59:	learn: 0.4047833	test: 0.4356222	best: 0.4356222 (59)	total: 943ms	remaining: 14.8s
60:	learn: 0.4037233	test: 0.4341761	best: 0.4341761 (60)	total: 955ms	remaining: 14.7s
61:	learn: 0.4020346	test: 0.4330486	best: 0.4330486 (61)	total: 968ms	remaining: 14.6s
62:	learn: 0.3996695	test: 0.4335134	best: 0.4330486 (61)	total: 982ms	remaining: 14.6s
63:	learn: 0.3985632	test: 0.4323146	best: 0.4323146 (63)	total: 995ms	remaining: 14.6s
64:	learn: 0.3975079	test: 0.4318979	best: 0.4318979 (64)	total: 1.01s	remaining: 14.5s
65:	learn: 0.3968876	test: 0.4311525	best: 0.4311525 (65)	total: 1.02s	remaining: 14.4s
66:	learn: 0.3962620	test: 0.4302197	best: 0.4302197 (66)	total: 1.03s	remaining: 14.3s
67:	learn: 0.3956378	test: 0.4292186	best: 0.4292186 (67)	total: 1.04s	remaining: 14.3s
68:	learn: 0.3938460	test: 0.4288455	best: 0.4288455 (68)	total: 1.05s	remaining: 14.2s
69:	learn: 0.3928599	test: 0.4281878	best: 0.4281878 (69)	total: 1.06s	remaining: 14.2s
70:	learn: 0.3926054	test: 0.4274335	best: 0.4274335 (70)	total: 1.07s	remaining: 14s
71:	learn: 0.3913051	test: 0.4266917	best: 0.4266917 (71)	total: 1.08s	remaining: 13.9s
72:	learn: 0.3909012	test: 0.4265089	best: 0.4265089 (72)	total: 1.09s	remaining: 13.9s
73:	learn: 0.3907598	test: 0.4262910	best: 0.4262910 (73)	total: 1.11s	remaining: 13.9s
74:	learn: 0.3903216	test: 0.4259925	best: 0.4259925 (74)	total: 1.12s	remaining: 13.8s
75:	learn: 0.3888746	test: 0.4249856	best: 0.4249856 (75)	total: 1.13s	remaining: 13.8s
76:	learn: 0.3884875	test: 0.4248116	best: 0.4248116 (76)	total: 1.15s	remaining: 13.7s
77:	learn: 0.3867381	test: 0.4242967	best: 0.4242967 (77)	total: 1.16s	remaining: 13.7s
78:	learn: 0.3858845	test: 0.4239430	best: 0.4239430 (78)	total: 1.17s	remaining: 13.6s
79:	learn: 0.3849723	test: 0.4224345	best: 0.4224345 (79)	total: 1.18s	remaining: 13.6s
80:	learn: 0.3832013	test: 0.4219659	best: 0.4219659 (80)	total: 1.19s	remaining: 13.5s
81:	learn: 0.3820908	test: 0.4218923	best: 0.4218923 (81)	total: 1.2s	remaining: 13.5s
82:	learn: 0.3811522	test: 0.4211551	best: 0.4211551 (82)	total: 1.22s	remaining: 13.4s
83:	learn: 0.3802925	test: 0.4204532	best: 0.4204532 (83)	total: 1.23s	remaining: 13.4s
84:	learn: 0.3793771	test: 0.4196669	best: 0.4196669 (84)	total: 1.24s	remaining: 13.4s
85:	learn: 0.3792169	test: 0.4191401	best: 0.4191401 (85)	total: 1.25s	remaining: 13.2s
86:	learn: 0.3782712	test: 0.4185471	best: 0.4185471 (86)	total: 1.26s	remaining: 13.2s
87:	learn: 0.3774515	test: 0.4181844	best: 0.4181844 (87)	total: 1.28s	remaining: 13.3s
88:	learn: 0.3769812	test: 0.4176166	best: 0.4176166 (88)	total: 1.29s	remaining: 13.2s
89:	learn: 0.3764736	test: 0.4167529	best: 0.4167529 (89)	total: 1.3s	remaining: 13.2s
90:	learn: 0.3754115	test: 0.4168682	best: 0.4167529 (89)	total: 1.32s	remaining: 13.2s
91:	learn: 0.3747144	test: 0.4166072	best: 0.4166072 (91)	total: 1.33s	remaining: 13.1s
92:	learn: 0.3745580	test: 0.4164312	best: 0.4164312 (92)	total: 1.34s	remaining: 13s
93:	learn: 0.3742689	test: 0.4163285	best: 0.4163285 (93)	total: 1.35s	remaining: 13s
94:	learn: 0.3738528	test: 0.4159777	best: 0.4159777 (94)	total: 1.36s	remaining: 13s
95:	learn: 0.3733778	test: 0.4157516	best: 0.4157516 (95)	total: 1.37s	remaining: 12.9s
96:	learn: 0.3728777	test: 0.4156969	best: 0.4156969 (96)	total: 1.39s	remaining: 12.9s
97:	learn: 0.3722808	test: 0.4148254	best: 0.4148254 (97)	total: 1.4s	remaining: 12.9s
98:	learn: 0.3715320	test: 0.4142153	best: 0.4142153 (98)	total: 1.41s	remaining: 12.9s
99:	learn: 0.3713123	test: 0.4137836	best: 0.4137836 (99)	total: 1.42s	remaining: 12.8s
100:	learn: 0.3711681	test: 0.4134127	best: 0.4134127 (100)	total: 1.43s	remaining: 12.7s
101:	learn: 0.3701463	test: 0.4129498	best: 0.4129498 (101)	total: 1.44s	remaining: 12.7s
102:	learn: 0.3696277	test: 0.4126316	best: 0.4126316 (102)	total: 1.45s	remaining: 12.7s
103:	learn: 0.3687955	test: 0.4111648	best: 0.4111648 (103)	total: 1.47s	remaining: 12.6s
104:	learn: 0.3680006	test: 0.4103194	best: 0.4103194 (104)	total: 1.48s	remaining: 12.6s
105:	learn: 0.3678460	test: 0.4103092	best: 0.4103092 (105)	total: 1.49s	remaining: 12.5s
106:	learn: 0.3672394	test: 0.4097549	best: 0.4097549 (106)	total: 1.5s	remaining: 12.6s
107:	learn: 0.3672117	test: 0.4097518	best: 0.4097518 (107)	total: 1.51s	remaining: 12.5s
108:	learn: 0.3665546	test: 0.4096297	best: 0.4096297 (108)	total: 1.53s	remaining: 12.5s
109:	learn: 0.3655739	test: 0.4091176	best: 0.4091176 (109)	total: 1.54s	remaining: 12.5s
110:	learn: 0.3654657	test: 0.4088216	best: 0.4088216 (110)	total: 1.54s	remaining: 12.4s
111:	learn: 0.3646549	test: 0.4087192	best: 0.4087192 (111)	total: 1.56s	remaining: 12.3s
112:	learn: 0.3634674	test: 0.4075590	best: 0.4075590 (112)	total: 1.57s	remaining: 12.3s
113:	learn: 0.3630065	test: 0.4073434	best: 0.4073434 (113)	total: 1.58s	remaining: 12.3s
114:	learn: 0.3624458	test: 0.4074634	best: 0.4073434 (113)	total: 1.59s	remaining: 12.3s
115:	learn: 0.3616972	test: 0.4071796	best: 0.4071796 (115)	total: 1.6s	remaining: 12.2s
116:	learn: 0.3615271	test: 0.4071387	best: 0.4071387 (116)	total: 1.62s	remaining: 12.3s
117:	learn: 0.3614277	test: 0.4072280	best: 0.4071387 (116)	total: 1.63s	remaining: 12.2s
118:	learn: 0.3603144	test: 0.4062959	best: 0.4062959 (118)	total: 1.64s	remaining: 12.2s
119:	learn: 0.3599630	test: 0.4062330	best: 0.4062330 (119)	total: 1.66s	remaining: 12.1s
120:	learn: 0.3592807	test: 0.4058909	best: 0.4058909 (120)	total: 1.67s	remaining: 12.1s
121:	learn: 0.3587751	test: 0.4056309	best: 0.4056309 (121)	total: 1.68s	remaining: 12.1s
122:	learn: 0.3583614	test: 0.4056128	best: 0.4056128 (122)	total: 1.69s	remaining: 12.1s
123:	learn: 0.3580264	test: 0.4054937	best: 0.4054937 (123)	total: 1.71s	remaining: 12s
124:	learn: 0.3574388	test: 0.4057917	best: 0.4054937 (123)	total: 1.72s	remaining: 12s
125:	learn: 0.3567530	test: 0.4055021	best: 0.4054937 (123)	total: 1.73s	remaining: 12s
126:	learn: 0.3561015	test: 0.4053356	best: 0.4053356 (126)	total: 1.74s	remaining: 12s
127:	learn: 0.3558349	test: 0.4051968	best: 0.4051968 (127)	total: 1.75s	remaining: 12s
128:	learn: 0.3558348	test: 0.4051966	best: 0.4051966 (128)	total: 1.76s	remaining: 11.9s
129:	learn: 0.3552632	test: 0.4059886	best: 0.4051966 (128)	total: 1.77s	remaining: 11.8s
130:	learn: 0.3551325	test: 0.4060901	best: 0.4051966 (128)	total: 1.78s	remaining: 11.8s
131:	learn: 0.3549291	test: 0.4058885	best: 0.4051966 (128)	total: 1.8s	remaining: 11.8s
132:	learn: 0.3541760	test: 0.4056387	best: 0.4051966 (128)	total: 1.81s	remaining: 11.8s
133:	learn: 0.3541024	test: 0.4056707	best: 0.4051966 (128)	total: 1.82s	remaining: 11.7s
134:	learn: 0.3540080	test: 0.4053516	best: 0.4051966 (128)	total: 1.82s	remaining: 11.7s
135:	learn: 0.3534041	test: 0.4049094	best: 0.4049094 (135)	total: 1.83s	remaining: 11.7s
136:	learn: 0.3531427	test: 0.4047992	best: 0.4047992 (136)	total: 1.85s	remaining: 11.6s
137:	learn: 0.3526642	test: 0.4042061	best: 0.4042061 (137)	total: 1.86s	remaining: 11.6s
138:	learn: 0.3517461	test: 0.4038863	best: 0.4038863 (138)	total: 1.87s	remaining: 11.6s
139:	learn: 0.3510655	test: 0.4031374	best: 0.4031374 (139)	total: 1.89s	remaining: 11.6s
140:	learn: 0.3508675	test: 0.4030210	best: 0.4030210 (140)	total: 1.9s	remaining: 11.6s
141:	learn: 0.3499321	test: 0.4032275	best: 0.4030210 (140)	total: 1.91s	remaining: 11.6s
142:	learn: 0.3498985	test: 0.4032541	best: 0.4030210 (140)	total: 1.92s	remaining: 11.5s
143:	learn: 0.3492545	test: 0.4027983	best: 0.4027983 (143)	total: 1.94s	remaining: 11.5s
144:	learn: 0.3489518	test: 0.4024768	best: 0.4024768 (144)	total: 1.95s	remaining: 11.5s
145:	learn: 0.3485265	test: 0.4021110	best: 0.4021110 (145)	total: 1.97s	remaining: 11.5s
146:	learn: 0.3481955	test: 0.4021177	best: 0.4021110 (145)	total: 1.98s	remaining: 11.5s
147:	learn: 0.3472829	test: 0.4017109	best: 0.4017109 (147)	total: 2s	remaining: 11.5s
148:	learn: 0.3461772	test: 0.4010244	best: 0.4010244 (148)	total: 2.01s	remaining: 11.5s
149:	learn: 0.3456412	test: 0.4011647	best: 0.4010244 (148)	total: 2.02s	remaining: 11.5s
150:	learn: 0.3448945	test: 0.4008998	best: 0.4008998 (150)	total: 2.03s	remaining: 11.4s
151:	learn: 0.3445742	test: 0.4008529	best: 0.4008529 (151)	total: 2.05s	remaining: 11.4s
152:	learn: 0.3443865	test: 0.4011244	best: 0.4008529 (151)	total: 2.06s	remaining: 11.4s
153:	learn: 0.3439867	test: 0.4013078	best: 0.4008529 (151)	total: 2.07s	remaining: 11.4s
154:	learn: 0.3437705	test: 0.4014411	best: 0.4008529 (151)	total: 2.08s	remaining: 11.4s
155:	learn: 0.3433918	test: 0.4014422	best: 0.4008529 (151)	total: 2.1s	remaining: 11.3s
156:	learn: 0.3430506	test: 0.4010456	best: 0.4008529 (151)	total: 2.11s	remaining: 11.3s
157:	learn: 0.3425827	test: 0.4006976	best: 0.4006976 (157)	total: 2.12s	remaining: 11.3s
158:	learn: 0.3425424	test: 0.4006983	best: 0.4006976 (157)	total: 2.13s	remaining: 11.2s
159:	learn: 0.3420207	test: 0.4000189	best: 0.4000189 (159)	total: 2.14s	remaining: 11.2s
160:	learn: 0.3419138	test: 0.3998793	best: 0.3998793 (160)	total: 2.15s	remaining: 11.2s
161:	learn: 0.3414931	test: 0.3995573	best: 0.3995573 (161)	total: 2.16s	remaining: 11.2s
162:	learn: 0.3408225	test: 0.3996494	best: 0.3995573 (161)	total: 2.17s	remaining: 11.2s
163:	learn: 0.3406300	test: 0.3997179	best: 0.3995573 (161)	total: 2.19s	remaining: 11.1s
164:	learn: 0.3406300	test: 0.3997178	best: 0.3995573 (161)	total: 2.19s	remaining: 11.1s
165:	learn: 0.3401746	test: 0.3994599	best: 0.3994599 (165)	total: 2.2s	remaining: 11.1s
166:	learn: 0.3395949	test: 0.3996377	best: 0.3994599 (165)	total: 2.21s	remaining: 11s
167:	learn: 0.3395949	test: 0.3996377	best: 0.3994599 (165)	total: 2.22s	remaining: 11s
168:	learn: 0.3391894	test: 0.3995142	best: 0.3994599 (165)	total: 2.23s	remaining: 11s
169:	learn: 0.3391193	test: 0.3996210	best: 0.3994599 (165)	total: 2.24s	remaining: 10.9s
170:	learn: 0.3384840	test: 0.3994490	best: 0.3994490 (170)	total: 2.25s	remaining: 10.9s
171:	learn: 0.3383553	test: 0.3992721	best: 0.3992721 (171)	total: 2.26s	remaining: 10.9s
172:	learn: 0.3379379	test: 0.3991737	best: 0.3991737 (172)	total: 2.27s	remaining: 10.9s
173:	learn: 0.3372661	test: 0.3988482	best: 0.3988482 (173)	total: 2.29s	remaining: 10.9s
174:	learn: 0.3369315	test: 0.3988157	best: 0.3988157 (174)	total: 2.3s	remaining: 10.8s
175:	learn: 0.3366366	test: 0.3989402	best: 0.3988157 (174)	total: 2.31s	remaining: 10.8s
176:	learn: 0.3361743	test: 0.3987077	best: 0.3987077 (176)	total: 2.32s	remaining: 10.8s
177:	learn: 0.3360778	test: 0.3986783	best: 0.3986783 (177)	total: 2.33s	remaining: 10.8s
178:	learn: 0.3355855	test: 0.3986022	best: 0.3986022 (178)	total: 2.36s	remaining: 10.8s
179:	learn: 0.3354023	test: 0.3985949	best: 0.3985949 (179)	total: 2.38s	remaining: 10.8s
180:	learn: 0.3352007	test: 0.3985678	best: 0.3985678 (180)	total: 2.39s	remaining: 10.8s
181:	learn: 0.3344942	test: 0.3985312	best: 0.3985312 (181)	total: 2.41s	remaining: 10.8s
182:	learn: 0.3340321	test: 0.3986521	best: 0.3985312 (181)	total: 2.42s	remaining: 10.8s
183:	learn: 0.3333556	test: 0.3985747	best: 0.3985312 (181)	total: 2.43s	remaining: 10.8s
184:	learn: 0.3330068	test: 0.3982813	best: 0.3982813 (184)	total: 2.44s	remaining: 10.8s
185:	learn: 0.3329832	test: 0.3982824	best: 0.3982813 (184)	total: 2.45s	remaining: 10.7s
186:	learn: 0.3323023	test: 0.3980368	best: 0.3980368 (186)	total: 2.46s	remaining: 10.7s
187:	learn: 0.3322699	test: 0.3978982	best: 0.3978982 (187)	total: 2.46s	remaining: 10.6s
188:	learn: 0.3314343	test: 0.3981615	best: 0.3978982 (187)	total: 2.48s	remaining: 10.6s
189:	learn: 0.3312888	test: 0.3981433	best: 0.3978982 (187)	total: 2.49s	remaining: 10.6s
190:	learn: 0.3309874	test: 0.3980582	best: 0.3978982 (187)	total: 2.5s	remaining: 10.6s
191:	learn: 0.3307796	test: 0.3980432	best: 0.3978982 (187)	total: 2.52s	remaining: 10.6s
192:	learn: 0.3306578	test: 0.3979033	best: 0.3978982 (187)	total: 2.53s	remaining: 10.6s
193:	learn: 0.3299342	test: 0.3978205	best: 0.3978205 (193)	total: 2.54s	remaining: 10.6s
194:	learn: 0.3291373	test: 0.3965197	best: 0.3965197 (194)	total: 2.55s	remaining: 10.5s
195:	learn: 0.3285707	test: 0.3970109	best: 0.3965197 (194)	total: 2.56s	remaining: 10.5s
196:	learn: 0.3282818	test: 0.3967007	best: 0.3965197 (194)	total: 2.58s	remaining: 10.5s
197:	learn: 0.3273962	test: 0.3968371	best: 0.3965197 (194)	total: 2.59s	remaining: 10.5s
198:	learn: 0.3272150	test: 0.3966213	best: 0.3965197 (194)	total: 2.6s	remaining: 10.5s
199:	learn: 0.3266134	test: 0.3968475	best: 0.3965197 (194)	total: 2.61s	remaining: 10.4s
200:	learn: 0.3265759	test: 0.3967844	best: 0.3965197 (194)	total: 2.62s	remaining: 10.4s
201:	learn: 0.3261540	test: 0.3968244	best: 0.3965197 (194)	total: 2.63s	remaining: 10.4s
202:	learn: 0.3261539	test: 0.3968187	best: 0.3965197 (194)	total: 2.64s	remaining: 10.4s
203:	learn: 0.3256543	test: 0.3967295	best: 0.3965197 (194)	total: 2.65s	remaining: 10.3s
204:	learn: 0.3255014	test: 0.3965655	best: 0.3965197 (194)	total: 2.66s	remaining: 10.3s
205:	learn: 0.3254665	test: 0.3965661	best: 0.3965197 (194)	total: 2.67s	remaining: 10.3s
206:	learn: 0.3251494	test: 0.3965013	best: 0.3965013 (206)	total: 2.68s	remaining: 10.3s
207:	learn: 0.3251059	test: 0.3965028	best: 0.3965013 (206)	total: 2.68s	remaining: 10.2s
208:	learn: 0.3247632	test: 0.3964637	best: 0.3964637 (208)	total: 2.69s	remaining: 10.2s
209:	learn: 0.3245387	test: 0.3965367	best: 0.3964637 (208)	total: 2.7s	remaining: 10.2s
210:	learn: 0.3237341	test: 0.3961856	best: 0.3961856 (210)	total: 2.71s	remaining: 10.2s
211:	learn: 0.3233256	test: 0.3958950	best: 0.3958950 (211)	total: 2.73s	remaining: 10.1s
212:	learn: 0.3232958	test: 0.3958835	best: 0.3958835 (212)	total: 2.73s	remaining: 10.1s
213:	learn: 0.3229699	test: 0.3959873	best: 0.3958835 (212)	total: 2.74s	remaining: 10.1s
214:	learn: 0.3225119	test: 0.3952189	best: 0.3952189 (214)	total: 2.76s	remaining: 10.1s
215:	learn: 0.3217883	test: 0.3965330	best: 0.3952189 (214)	total: 2.77s	remaining: 10.1s
216:	learn: 0.3211591	test: 0.3967155	best: 0.3952189 (214)	total: 2.78s	remaining: 10s
217:	learn: 0.3201619	test: 0.3964230	best: 0.3952189 (214)	total: 2.8s	remaining: 10s
218:	learn: 0.3197642	test: 0.3959198	best: 0.3952189 (214)	total: 2.81s	remaining: 10s
219:	learn: 0.3196206	test: 0.3959552	best: 0.3952189 (214)	total: 2.82s	remaining: 10s
220:	learn: 0.3196179	test: 0.3959507	best: 0.3952189 (214)	total: 2.83s	remaining: 9.96s
221:	learn: 0.3194516	test: 0.3959052	best: 0.3952189 (214)	total: 2.84s	remaining: 9.95s
222:	learn: 0.3194493	test: 0.3959052	best: 0.3952189 (214)	total: 2.84s	remaining: 9.9s
223:	learn: 0.3194209	test: 0.3958553	best: 0.3952189 (214)	total: 2.85s	remaining: 9.89s
224:	learn: 0.3191671	test: 0.3956713	best: 0.3952189 (214)	total: 2.87s	remaining: 9.88s

CatBoostClassifier(custom_loss=['Accuracy'], random_seed=42)

In [44]:
model.tree_count_

284

#### Важность признаков 

CatBoost поддерживает несколько способов вычисления важности признаков, в том числе широко применяемый сейчас подход Shap (про него поговорим в следующих модулях).

In [48]:
feature_importances = model.get_feature_importance()

feature_names = Xtrain.columns
for score, name in sorted(zip(feature_importances, feature_names), reverse=True):
    print('{}: {}'.format(name, score))

Sex: 28.377591527551807
Pclass: 17.450379813673287
Parch: 10.276200044515498
Embarked: 8.761954037905873
Cabin: 8.281577549519369
SibSp: 7.950157281933983
Age: 7.842375602284014
Ticket: 5.620556803330715
Fare: 5.4392073392855105
PassengerId: 0.0
Name: 0.0

#### Сохранение модели

In [49]:
# сохраняем модель
model.save_model('catboost_model.dump')

# загружаем сохраненную модель
model.load_model('catboost_model.dump');